### ISSUE TITLE
Issue with custom metrics

### ISSUE THREAD

**Issue by websystem3** [nickfloyd/newrelic-perfmon-plugin#12]
When I try to run custom metrics I get this error.  

C:/Windows/TEMP/ocr6291.tmp/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 8 column 3 (Psych::SyntaxError)
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/1.9.1/psych.rb:203:in`parse_stream'
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/1.9.1/psych.rb:151:in `parse'
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/1.9.1/psych.rb:127:in`load'
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/gems/1.9.1/gems/newrelic_plugin-1.2.1/lib/newrelic_plugin/config.rb:28:in `initialize'
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/gems/1.9.1/gems/newrelic_plugin-1.2.1/lib/newrelic_plugin/config.rb:78:in`new'
    from C:/Windows/TEMP/ocr6291.tmp/lib/ruby/gems/1.9.1/gems/newrelic_plugin-1.2.1/lib/newrelic_plugin/config.rb:78:in `config'
    from C:/Windows/TEMP/ocr6291.tmp/src/perfmon_plugin_multithread.rb:22:in`class:Agent'
    from C:/Windows/TEMP/ocr6291.tmp/src/perfmon_plugin_multithread.rb:12:in `<module:PerfmonAgent>'
    from C:/Windows/TEMP/ocr6291.tmp/src/perfmon_plugin_multithread.rb:10:in`<main>'

If I use the built in metrics I have no problems.

**Comment by theskipster** [comment]
I get the same error.
